# Generated by Django 2.2.8 on 2020-01-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modify_date',
            new_name='modify_dt',
        ),
    ]
